//CART
export const ADD_ITEM_TO_CART = "ADD_ITEM_TO_CART"
export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM"
export const PLUS_CART_ITEM = "PLUS_CART_ITEM"
export const MINUS_CART_ITEM = "MINUS_CART_ITEM"
export const CLEAR_CART = "CLEAR_CART"
//CART

//CATEGORY
export const SET_CATEGORY = "SET_CATEGORY"
export const SELECT_CATEGORY = "SELECT_CATEGORY"
//CATEGORY

//FILTERS
export const SET_SORT_BY = "SET_SORT_BY"
//FILTERS

//PRODUCTS
export const SET_PRODUCTS = "SET_PRODUCTS"
export const SET_LOADED = "SET_LOADED"
//PRODUCTS

export const SET_VISIBLE_MENU = "SET_VISIBLE_MENU"